<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Tenant\Lookup\Currency;

class CurrencySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 */
	public function run(): void
	{
		Currency::truncate();
  
		$currencies = [
		['currency' =>'AED' , 'name' => 'Dirhams', 'country' => 'United Arab Emirates', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'AFN' , 'name' => 'Afghanis', 'country' => 'Afghanistan', 'symbol' => 'Ø‹', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ALL' , 'name' => 'Leke', 'country' => 'Albania', 'symbol' => 'Lek', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'AMD' , 'name' => 'Drams', 'country' => 'Armenia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ANG' , 'name' => 'Guilders (also called Florins)', 'country' => 'Netherlands Antilles', 'symbol' => 'Æ’', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'AOA' , 'name' => 'Kwanza', 'country' => 'Angola', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ARS' , 'name' => 'Pesos', 'country' => 'Argentina', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'AUD' , 'name' => 'Dollars', 'country' => 'Australia', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>FALSE],
		['currency' =>'AWG' , 'name' => 'Guilders (also called Florins)', 'country' => 'Aruba', 'symbol' => 'Æ’', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'AZN' , 'name' => 'New Manats', 'country' => 'Azerbaijan', 'symbol' => 'Ð¼Ð°Ð½', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BAM' , 'name' => 'Convertible Marka', 'country' => 'Bosnia and Herzegovina', 'symbol' => 'KM', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BBD' , 'name' => 'Dollars', 'country' => 'Barbados', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BDT' , 'name' => 'Taka', 'country' => 'Bangladesh', 'symbol' => 'à§³', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BGN' , 'name' => 'Leva', 'country' => 'Bulgaria', 'symbol' => 'Ð»Ð²', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BHD' , 'name' => 'Dinars', 'country' => 'Bahrain', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BIF' , 'name' => 'Francs', 'country' => 'Burundi', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BMD' , 'name' => 'Dollars', 'country' => 'Bermuda', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BND' , 'name' => 'Dollars', 'country' => 'Brunei Darussalam', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BOB' , 'name' => 'Bolivianos', 'country' => 'Bolivia', 'symbol' => '$b', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BRL' , 'name' => 'Brazil Real', 'country' => 'Brazil', 'symbol' => 'R$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BSD' , 'name' => 'Dollars', 'country' => 'Bahamas', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BTN' , 'name' => 'Ngultrum', 'country' => 'Bhutan', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BWP' , 'name' => 'Pulas', 'country' => 'Botswana', 'symbol' => 'P', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'BYR' , 'name' => 'Rubles', 'country' => 'Belarus', 'symbol' => 'â‚½', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'BZD' , 'name' => 'Dollars', 'country' => 'Belize', 'symbol' => 'BZ$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CAD' , 'name' => 'Dollars', 'country' => 'Canada', 'symbol' => '$', 'enable'=>TRUE, 'rates'=>TRUE, 'never'=>FALSE],
		['currency' =>'CDF' , 'name' => 'Congolese Francs', 'country' => 'Congo/Kinshasa', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CHF' , 'name' => 'Francs', 'country' => 'Switzerland', 'symbol' => 'CHF', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CLP' , 'name' => 'Pesos', 'country' => 'Chile', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CNY' , 'name' => 'Yuan Renminbi', 'country' => 'China', 'symbol' => 'Â¥', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'COP' , 'name' => 'Pesos', 'country' => 'Columbia', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CRC' , 'name' => 'Colones', 'country' => 'Costa Rica', 'symbol' => 'â‚¡', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CUP' , 'name' => 'Pesos', 'country' => 'Cuba', 'symbol' => 'â‚±', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CVE' , 'name' => 'Escudos', 'country' => 'Cape Verde', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CZK' , 'name' => 'Koruny', 'country' => 'Czech Republic', 'symbol' => 'KÄ', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'DJF' , 'name' => 'Francs', 'country' => 'Djibouti', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'DKK' , 'name' => 'Kroner', 'country' => 'Denmark', 'symbol' => 'kr', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'DOP' , 'name' => 'Pesos', 'country' => 'Dominican Republic', 'symbol' => 'RD$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'DZD' , 'name' => 'Algeria Dinars', 'country' => 'Algeria', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'EEK' , 'name' => 'Krooni', 'country' => 'Estonia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'EGP' , 'name' => 'Pounds', 'country' => 'Egypt', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ERN' , 'name' => 'Nakfa', 'country' => 'Eritrea', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ETB' , 'name' => 'Birr', 'country' => 'Ethopia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'EUR' , 'name' => 'Euro', 'country' => 'Euro Member Countries', 'symbol' => 'â‚¬', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>FALSE],
		['currency' =>'FJD' , 'name' => 'Dollars', 'country' => 'Fiji', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'FKP' , 'name' => 'Pounds', 'country' => 'Falkland Islands (Malvinas)', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GBP' , 'name' => 'Pounds', 'country' => 'United Kingdom', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>FALSE],
		['currency' =>'GEL' , 'name' => 'Lari', 'country' => 'Georgia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GGP' , 'name' => 'Pounds', 'country' => 'Guernsey', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GHS' , 'name' => 'Cedis', 'country' => 'Ghana', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GIP' , 'name' => 'Pounds', 'country' => 'Gibraltar', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GMD' , 'name' => 'Dalasi', 'country' => 'Gambia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GNF' , 'name' => 'Francs', 'country' => 'Guinea', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GTQ' , 'name' => 'Quetzales', 'country' => 'Guatemala', 'symbol' => 'Q', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'GYD' , 'name' => 'Dollars', 'country' => 'Guyana', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'HKD' , 'name' => 'Dollars', 'country' => 'Hong Kong', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'HNL' , 'name' => 'Lempiras', 'country' => 'Honduras', 'symbol' => 'L', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'HRK' , 'name' => 'Kuna', 'country' => 'Croatia', 'symbol' => 'kn', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'HTG' , 'name' => 'Gourdes', 'country' => 'Haiti', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'HUF' , 'name' => 'Forint', 'country' => 'Hungary', 'symbol' => 'Ft', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'IDR' , 'name' => 'Rupiahs', 'country' => 'Indonesia', 'symbol' => 'Rp', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ILS' , 'name' => 'New Shekels', 'country' => 'Israel', 'symbol' => 'â‚ª', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'IMP' , 'name' => 'Pounds', 'country' => 'Isle of Man', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'INR' , 'name' => 'Rupees', 'country' => 'India', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'IQD' , 'name' => 'Dinars', 'country' => 'Iraq', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'IRR' , 'name' => 'Rials', 'country' => 'Iran', 'symbol' => 'ï·¼', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ISK' , 'name' => 'Kronur', 'country' => 'Iceland', 'symbol' => 'kr', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'JEP' , 'name' => 'Pounds', 'country' => 'Jersey', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'JMD' , 'name' => 'Dollars', 'country' => 'Jamaica', 'symbol' => 'J$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'JOD' , 'name' => 'Dinars', 'country' => 'Jordan', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'JPY' , 'name' => 'Yen', 'country' => 'Japan', 'symbol' => 'Â¥', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>FALSE],
		['currency' =>'KES' , 'name' => 'Shillings', 'country' => 'Kenya', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KGS' , 'name' => 'Soms', 'country' => 'Kyrgyzstan', 'symbol' => 'Ð»Ð²', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KHR' , 'name' => 'Riels', 'country' => 'Cambodia', 'symbol' => 'áŸ›', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KMF' , 'name' => 'Francs', 'country' => 'Comoros', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KPW' , 'name' => 'Won', 'country' => 'Korea (North)', 'symbol' => 'â‚©', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KRW' , 'name' => 'Won', 'country' => 'Korea (South)', 'symbol' => 'â‚©', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KWD' , 'name' => 'Dinars', 'country' => 'Kuwait', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KYD' , 'name' => 'Dollars', 'country' => 'Cayman Islands', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'KZT' , 'name' => 'Tenge', 'country' => 'Kazakhstan', 'symbol' => 'Ð»Ð²', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'LAK' , 'name' => 'Kips', 'country' => 'Laos', 'symbol' => 'â‚­', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'LBP' , 'name' => 'Pounds', 'country' => 'Lebanon', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'LKR' , 'name' => 'Rupees', 'country' => 'Sri Lanka', 'symbol' => 'â‚¨', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'LRD' , 'name' => 'Dollars', 'country' => 'Liberia', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'LSL' , 'name' => 'Maloti', 'country' => 'Lesotho', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'LTL' , 'name' => 'Litai', 'country' => 'Lithuania', 'symbol' => 'Lt', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'LVL' , 'name' => 'Lati', 'country' => 'Latvia', 'symbol' => 'Ls', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'LYD' , 'name' => 'Dinars', 'country' => 'Libya', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MAD' , 'name' => 'Dirhams', 'country' => 'Morocco', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MDL' , 'name' => 'Dei', 'country' => 'Moldova', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MGA' , 'name' => 'Ariary', 'country' => 'Madagascar', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MKD' , 'name' => 'Denars', 'country' => 'Macedonia', 'symbol' => 'Ð´ÐµÐ½', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MMK' , 'name' => 'Kyats', 'country' => 'Myanmar (Burma)', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MNT' , 'name' => 'Tugriks', 'country' => 'Mongolia', 'symbol' => 'â‚®', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MOP' , 'name' => 'Patacas', 'country' => 'Macau', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MRO' , 'name' => 'Ouguiyas', 'country' => 'Mauritania', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'MUR' , 'name' => 'Rupees', 'country' => 'Mauritius', 'symbol' => 'â‚¨', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MVR' , 'name' => 'Rufiyaa', 'country' => 'Maldives (Maldive Islands)', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MWK' , 'name' => 'Kwachas', 'country' => 'Malawi', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MXN' , 'name' => 'Pesos', 'country' => 'Mexico', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MYR' , 'name' => 'Ringgits', 'country' => 'Malaysia', 'symbol' => 'RM', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MZN' , 'name' => 'Meticais', 'country' => 'Mozambique', 'symbol' => 'MT', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'NAD' , 'name' => 'Dollars', 'country' => 'Namibia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'NGN' , 'name' => 'Nairas', 'country' => 'Nigeria', 'symbol' => 'â‚¦', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'NIO' , 'name' => 'Cordobas', 'country' => 'Nicaragua', 'symbol' => 'C$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'NOK' , 'name' => 'Krone', 'country' => 'Norway', 'symbol' => 'kr', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'NPR' , 'name' => 'Nepal Rupees', 'country' => 'Nepal', 'symbol' => 'â‚¨', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'NZD' , 'name' => 'Dollars', 'country' => 'New Zealand', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'OMR' , 'name' => 'Rials', 'country' => 'Oman', 'symbol' => 'ï·¼', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PAB' , 'name' => 'Balboa', 'country' => 'Panama', 'symbol' => 'B/.', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PEN' , 'name' => 'Nuevos Soles', 'country' => 'Peru', 'symbol' => 'S/.', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PGK' , 'name' => 'Kina', 'country' => 'Papua New Guinea', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PHP' , 'name' => 'Pesos', 'country' => 'Philippines', 'symbol' => 'Php', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PKR' , 'name' => 'Rupees', 'country' => 'Pakistan', 'symbol' => 'â‚¨', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PLN' , 'name' => 'Zlotych', 'country' => 'Poland', 'symbol' => 'zÅ‚', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'PYG' , 'name' => 'Guarani', 'country' => 'Paraguay', 'symbol' => 'Gs', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'QAR' , 'name' => 'Rials', 'country' => 'Qatar', 'symbol' => 'ï·¼', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'RON' , 'name' => 'New Lei', 'country' => 'Romania', 'symbol' => 'lei', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'RSD' , 'name' => 'Dinars', 'country' => 'Serbia', 'symbol' => 'Ð”Ð¸Ð½.', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'RUB' , 'name' => 'Rubles', 'country' => 'Russia', 'symbol' => 'Ñ€ÑƒÐ±', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'RWF' , 'name' => 'Rwanda Francs', 'country' => 'Rwanda', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SAR' , 'name' => 'Riyals', 'country' => 'Saudi Arabia', 'symbol' => 'ï·¼', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SBD' , 'name' => 'Dollars', 'country' => 'Solomon Islands', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SCR' , 'name' => 'Rupees', 'country' => 'Seychelles', 'symbol' => 'â‚¨', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SDG' , 'name' => 'Pounds', 'country' => 'Sudan', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SEK' , 'name' => 'Kronor', 'country' => 'Sweden', 'symbol' => 'kr', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SGD' , 'name' => 'Dollars', 'country' => 'Singapore', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SHP' , 'name' => 'Pounds', 'country' => 'Saint Helena', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SKK' , 'name' => 'Koruny', 'country' => 'Slovakia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'SLL' , 'name' => 'Leones', 'country' => 'Sierra Leone', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SOS' , 'name' => 'Shillings', 'country' => 'Somalia', 'symbol' => 'S', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SPL' , 'name' => 'Luigini', 'country' => 'Seborga', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'SRD' , 'name' => 'Dollars', 'country' => 'Suriname', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'STD' , 'name' => 'Dobras', 'country' => 'São Tome and Principe', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SVC' , 'name' => 'Colones', 'country' => 'El Salvador', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SYP' , 'name' => 'Pounds', 'country' => 'Syria', 'symbol' => 'Â£', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SZL' , 'name' => 'Emalangeni', 'country' => 'Swaziland', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'THB' , 'name' => 'Baht', 'country' => 'Thailand', 'symbol' => 'à¸¿', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TJS' , 'name' => 'Somoni', 'country' => 'Tajikistan', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TMM' , 'name' => 'Manats', 'country' => 'Turkmenistan', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'TND' , 'name' => 'Dinars', 'country' => 'Tunisia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TOP' , 'name' => 'Paanga', 'country' => 'Tonga', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TRY' , 'name' => 'New Lira', 'country' => 'Turkey', 'symbol' => 'TL', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TTD' , 'name' => 'Dollars', 'country' => 'Trinidad and Tobago', 'symbol' => 'TT$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TVD' , 'name' => 'Tuvalu Dollars', 'country' => 'Tuvalu', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'TWD' , 'name' => 'New Dollars', 'country' => 'Taiwan', 'symbol' => 'NT$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TZS' , 'name' => 'Shillings', 'country' => 'Tanzania', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'UAH' , 'name' => 'Hryvnia', 'country' => 'Ukraine', 'symbol' => 'â‚´', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'UGX' , 'name' => 'Shillings', 'country' => 'Uganda', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'USD' , 'name' => 'Dollars', 'country' => 'United States of America', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>FALSE],
		['currency' =>'UYU' , 'name' => 'Pesos', 'country' => 'Uruguay', 'symbol' => '$U', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'UZS' , 'name' => 'Sums', 'country' => 'Uzbekistan', 'symbol' => 'Ð»Ð²', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'VEF' , 'name' => 'Bolivares Fuertes', 'country' => 'Venezuela', 'symbol' => 'Bs', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'VND' , 'name' => 'Dong', 'country' => 'Viet Nam', 'symbol' => 'â‚«', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'VUV' , 'name' => 'Vatu', 'country' => 'Vanuatu', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'WST' , 'name' => 'Tala', 'country' => 'Samoa', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XAF' , 'name' => 'Francs', 'country' => 'Communauté Financière Africaine BEAC', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XAG' , 'name' => 'Ounces', 'country' => 'Silver', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XAU' , 'name' => 'Ounces', 'country' => 'Gold', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'XCD' , 'name' => 'Dollars', 'country' => 'East Caribbean', 'symbol' => '$', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XDR' , 'name' => 'Special Drawing Rights', 'country' => 'International Monetary Fund (IMF)', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XOF' , 'name' => 'Francs', 'country' => 'Communauté Financière Africaine BCEAO', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XPD' , 'name' => 'Ounces', 'country' => 'Palladium', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'XPF' , 'name' => 'Francs', 'country' => 'Comptoirs Français du Pacifique', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'XPT' , 'name' => 'Ounces', 'country' => 'Platinum', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'YER' , 'name' => 'Rials', 'country' => 'Yemen', 'symbol' => 'ï·¼', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ZAR' , 'name' => 'Rand', 'country' => 'South Africa', 'symbol' => 'R', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ZMK' , 'name' => 'Kwacha', 'country' => 'Zambia', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'ZWD' , 'name' => 'Zimbabwe Dollars', 'country' => 'Zimbabwe', 'symbol' => '', 'enable'=>FALSE, 'rates'=>FALSE, 'never'=>TRUE],
		['currency' =>'BYN' , 'name' => 'Belarusian Ruble', 'country' => 'Belarusian Ruble', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CLF' , 'name' => 'Chilean Unit of Account (UF)', 'country' => 'Chilean Unit of Account (UF)', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CNH' , 'name' => 'offshore RMB', 'country' => 'offshore RMB', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'CUC' , 'name' => 'Cuban Convertible Peso', 'country' => 'Cuban Convertible Peso', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'MRU' , 'name' => 'Mauritanian ouguiya', 'country' => 'Mauritanian ouguiya', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'SSP' , 'name' => 'South Sudanese Pound', 'country' => 'South Sudanese Pound', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'STN' , 'name' => 'Sao Tomean Dobra', 'country' => 'Sao Tomean Dobra', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'TMT' , 'name' => 'Turkmenistani Manat', 'country' => 'Turkmenistani Manat', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'VES' , 'name' => 'Venezuelan bolívar', 'country' => 'Venezuelan bolívar', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ZMW' , 'name' => 'Zambian Kwacha', 'country' => 'Zambian Kwacha', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
		['currency' =>'ZWL' , 'name' => 'Zimbabwean dollar', 'country' => 'Zimbabwean dollar', 'symbol' => '', 'enable'=>FALSE, 'rates'=>TRUE, 'never'=>TRUE],
	];

	foreach ($currencies as $key => $value) {
		Currency::create($value);
	}

	}
}
