<?php

namespace Database\Seeders\Landlord;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Landlord\Admin\Status;

class StatusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $statuses =  [
                [
                    'code'       => 1001,
                    'name'       => 'New',
                    'badge'      => 'info',
                    'accounts'   => false,
                    'services'   => false,
                    'tickets'    => true,
                    'checkouts'  => false,
                    'invoices'   => false,
                    'payments'   => false,
                ],
                [
                    'code'       => 1002,
                    'name'       => 'Draft',
                    'badge'      => 'info',
                    'accounts'   => false,
                    'services'   => true,
                    'tickets'    => false,
                    'checkouts'  => true,
                    'invoices'   => false,
                    'payments'   => true,
                ],
                [
                    'code'      => 1003,
                    'name'      => 'Active',
                    'badge'     => 'success',
                    'accounts'  => true,
                    'services'  => true,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1004,
                    'name'      => 'Assigned',
                    'badge'     => 'info',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1005,
                    'name'      => 'Pending',
                    'badge'     => 'danger',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1006,
                    'name'      => 'In-Progress',
                    'badge'     => 'primary',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1007,
                    'name'      => 'Internal Development',
                    'badge'     => 'primary',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],

                [
                    'code'      => 1008,
                    'name'      => 'Bug Fixing',
                    'badge'     => 'primary',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1009,
                    'name'      => 'Processing',
                    'badge'     => 'primary',
                    'accounts'  => false,
                    'services'  => true,
                    'tickets'   => false,
                    'checkouts' => true,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1010,
                    'name'      => 'Customer Working',
                    'badge'     => 'info',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1011,
                    'name'      => 'Resolved',
                    'badge'     => 'success',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1012,
                    'name'      => 'Closed',
                    'badge'     => 'success',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1013,
                    'name'      => 'Completed',
                    'badge'     => 'success',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => true,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1014,
                    'name'      => 'Paid',
                    'badge'     => 'success',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => true,
                    'payments'  => true,
                ],
                [
                    'code'      => 1015,
                    'name'      => 'On-Hold',
                    'badge'     => 'warning',
                    'accounts'  => true,
                    'services'  => false,
                    'tickets'   => true,
                    'checkouts' => false,
                    'invoices'  => true,
                    'payments'  => false,
                ],
                [
                    'code'      => 1016,
                    'name'      => 'Locked',
                    'badge'     => 'warning',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1017,
                    'name'      => 'Due',
                    'badge'     => 'warning',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => true,
                    'payments'  => false,
                ],
                [
                    'code'      => 1018,
                    'name'      => 'Past Due',
                    'badge'     => 'warning',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => true,
                    'payments'  => false,
                ],
                [
                    'code'      => 1019,
                    'name'      => 'Expired',
                    'badge'     => 'warning',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1020,
                    'name'      => 'Canceled',
                    'badge'     => 'warning',
                    'accounts'  => true,
                    'services'  => true,
                    'tickets'   => false,
                    'checkouts' => true,
                    'invoices'  => true,
                    'payments'  => true,
                ],
                [
                    'code'      => 1021,
                    'name'      => 'Failed',
                    'badge'     => 'danger',
                    'accounts'  => false,
                    'services'  => true,
                    'tickets'   => false,
                    'checkouts' => true,
                    'invoices'  => false,
                    'payments'  => true,
                ],
                [
                    'code'      => 1022,
                    'name'      => 'Error',
                    'badge'     => 'danger',
                    'accounts'  => false,
                    'services'  => true,
                    'tickets'   => false,
                    'checkouts' => true,
                    'invoices'  => false,
                    'payments'  => true,
                ],
                [
                    'code'      => 1023,
                    'name'      => 'Terminated',
                    'badge'     => 'danger',
                    'accounts'  => false,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
                [
                    'code'      => 1024,
                    'name'      => 'Archived',
                    'badge'     => 'secondary',
                    'accounts'  => true,
                    'services'  => false,
                    'tickets'   => false,
                    'checkouts' => false,
                    'invoices'  => false,
                    'payments'  => false,
                ],
        ];
        //
        Status::insert($statuses);
    }
}
