<?php

namespace Database\Seeders\Landlord;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Landlord\Manage\Status;

class StatusSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 */
	public function run(): void
	{
		$statuses = [
				[
					'code'		=> 'new', //1001,
					'name'		=> 'New',
					'badge'		=> 'info',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'draft',	//1002,
					'name'		=> 'Draft',
					'badge'		=> 'info',
					'accounts'	=> false,
					'services'	=> true,
					'tickets'	=> false,
					'checkouts' => true,
					'invoices'	=> false,
					'payments'	=> true,
				],
				[
					'code'		=> 'active', //1003,
					'name'		=> 'Active',
					'badge'		=> 'success',
					'accounts'	=> true,
					'services'	=> true,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'assigned', //1004,
					'name'		=> 'Assigned',
					'badge'		=> 'info',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'pending', //1005,
					'name'		=> 'Pending',
					'badge'		=> 'danger',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'in-progress', //1006,
					'name'		=> 'In-Progress',
					'badge'		=> 'primary',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'development', //1007,
					'name'		=> 'Development',
					'badge'		=> 'primary',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],

				[
					'code'		=> 'bug-fixing', //1008,
					'name'		=> 'Bug Fixing',
					'badge'		=> 'primary',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'processing', //1009,
					'name'		=> 'Processing',
					'badge'		=> 'danger',
					'accounts'	=> false,
					'services'	=> true,
					'tickets'	=> false,
					'checkouts' => true,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'cwip', //1010,
					'name'		=> 'Customer Working',
					'badge'		=> 'info',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'resolved', //1011,
					'name'		=> 'Resolved',
					'badge'		=> 'success',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'closed', //1012,
					'name'		=> 'Closed',
					'badge'		=> 'success',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'completed', //1013,
					'name'		=> 'Completed',
					'badge'		=> 'success',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => true,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'paid', //1014,
					'name'		=> 'Paid',
					'badge'		=> 'success',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> true,
					'payments'	=> true,
				],
				[
					'code'		=> 'on-hold', //1015,
					'name'		=> 'On-Hold',
					'badge'		=> 'warning',
					'accounts'	=> true,
					'services'	=> false,
					'tickets'	=> true,
					'checkouts' => false,
					'invoices'	=> true,
					'payments'	=> false,
				],
				[
					'code'		=> 'locked', //1016,
					'name'		=> 'Locked',
					'badge'		=> 'warning',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'due', //1017,
					'name'		=> 'Due',
					'badge'		=> 'warning',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> true,
					'payments'	=> false,
				],
				[
					'code'		=> 'past-due', //1018,
					'name'		=> 'Past Due',
					'badge'		=> 'warning',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> true,
					'payments'	=> false,
				],
				[
					'code'		=> 'expired', //1019,
					'name'		=> 'Expired',
					'badge'		=> 'warning',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'canceled', //1020,
					'name'		=> 'Canceled',
					'badge'		=> 'warning',
					'accounts'	=> true,
					'services'	=> true,
					'tickets'	=> false,
					'checkouts' => true,
					'invoices'	=> true,
					'payments'	=> true,
				],
				[
					'code'		=> 'failed', //1021,
					'name'		=> 'Failed',
					'badge'		=> 'danger',
					'accounts'	=> false,
					'services'	=> true,
					'tickets'	=> false,
					'checkouts' => true,
					'invoices'	=> false,
					'payments'	=> true,
				],
				[
					'code'		=> 'error', //1022,
					'name'		=> 'Error',
					'badge'		=> 'danger',
					'accounts'	=> false,
					'services'	=> true,
					'tickets'	=> false,
					'checkouts' => true,
					'invoices'	=> false,
					'payments'	=> true,
				],
				[
					'code'		=> 'terminated', //1023,
					'name'		=> 'Terminated',
					'badge'		=> 'danger',
					'accounts'	=> false,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
				[
					'code'		=> 'archived', //1024,
					'name'		=> 'Archived',
					'badge'		=> 'secondary',
					'accounts'	=> true,
					'services'	=> false,
					'tickets'	=> false,
					'checkouts' => false,
					'invoices'	=> false,
					'payments'	=> false,
				],
		];
		//
		Status::insert($statuses);
	}
}
